var GAME_LEVELS = [
    ["  xxxxxxx                                                                       ",
        "  x                                                                             ",
        "  x                                                                             ",
        "  x                                                                             ",
        "  x                                                                             ",
        "  x                                                                             ",
        "  x      yyy                                                                    ",
        "  x     yyyyy                                                                   ",
        "  x      yyy                                                                    ",
        "  x                  yyy                                                        ",
        "  x                 yyyyy                                                       ",
        "  xx                 yyy                                                        ",
        "  x                            uuu                                              ",
        "  x                           uuuuu                                             ",
        "  x                            uuu                                              ",
        "  x       yyy                                                                   ",
        "  x      yyyyy                                                                  ",
        "  x       yyy                                                                   ",
        "  x                                                                             ",
        "  xx                                                              xxx           ",
        "  x                 uuu                                          xx!xx          ",
        "  x                uuuuu                                         x!!!x          ",
        "  x                 uuu                                          xx!xx          ",
        "  xx                                                              xvx           ",
        "  x                                                                         xx  ",
        "  x                                                                          x  ",
        "  x             o                                        o                   x  ",
        "  xx                                                       F               o x  ",
        "  x                  p     p            o      o      o           xxx        x  ",
        "  x   @    s o      iiiiiiiii     x           g      x     x=    xxxxx      =x  ",
        "  xxxxxxxxxxxx                    xxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxx  ",
        "             x!!!!!!!!!!!!!!!!!!!!x                  x     x                    ",
        "             x!!!!!!!!!!!!!!!!!!!!x                  x!!!!!x                    ",
        "             x!!!!!!!!!!!!!!!!!!!!x                  x!!!!!x                    ",
        "             xxxxxxxxxxxxxxxxxxxxxx                  xxxxxxx                    ",
        "                                                                                ",
        "                                                                                "
    ],



    ["  xxxxxxx                                                                       ",
        "  x                                                                            x",
        "  x                                                                            x",
        "  x                                                                            x",
        "  x                                                                            x",
        "  x               xxxxx                                                        x",
        "  x                h  h                                                        x",
        "  x                                                                            x",
        "  x               h                                                            x",
        "  x                                                                            x",
        "  xx                                                                           x",
        "  xh                 h                                                         x",
        "  x               xxxxx        F                                               x",
        "  x       x   g   xxxxx    g   x                                               x",
        "  x       xxxxxxxxxxxxxxxxxxxxxx                                               x",
        "  xx                                                                           x",
        "  x                                                                            x",
        "  x                                                                            x",
        "  x                                                                            x",
        "  xx                                                                           x",
        "  x                                                                            x",
        "  x                         z                                                  x",
        "  x                 zzz                                                        x",
        "  xx                      z                                                    x",
        "  x          z  zzz z  z     z                                                 x",
        "  x                       x                                                    x",
        "  x         o   z  zz x z   z     o o                                   o     xx",
        "  xx        x  z                xxxxxzzzzzzxxxx                       suuu     x",
        "  x           x    z zzzz z zxz                                       uuuuu    x",
        "  x             z      z                                               uuu     x",
        "  x            x   z zz   z                            o                      xx",
        "  x                                                  syyy                      x",
        "  x                x                                 yyyyy          o          x",
        "  x                                                   yyy          yyy         x",
        "  x                                                               yyyyy       xx",
        "  x                                                                yyy         x",
        "  x                                                                     o      x",
        "  x                                                                    uuu     x",
        "  x                                                                   uuuuu   xx",
        "  x                                                                    uuu     x",
        "  x                                                                   o        x",
        "  x                                      !!!                         uuu       x",
        "  x                                     !xxx!                       uuuuu     xx",
        "  x                                    !x!!!x!                       uuu       x",
        "  x                                     x!!!x                                  x",
        "  x                                      xvx                                   x",
        "  x                                                                           xx",
        "  x                                                                            x",
        "  x                                                                            x",
        "  x                                          o     o     o       o       o     x",
        "  x    @                                 xx  =  x  =  x  =  x =  =   x   =   =xx",
        "  xxxxxxxxxzzzxxzzzzxxxxxxxxzzxxxxxzzzzzxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "          x!!!!!!!!!x    x!!!!!!x                                               ",
        "          xxxxxxxxxxx    xxxxxxxx                                               ",
        "                                                                                ",
        "                                                                                "
    ],



    ["  xxxxxxx                                                                       ",
        "  x                                                                            x",
        "  x                                 F                                          x",
        "  x                                                                            x",
        "  x                                                                            x",
        "  x                                 o                                          x",
        "  x                                 x                                          x",
        "  x                                                                            x",
        "  x                         p           p                                      x",
        "  x                         z    p      z                                      x",
        "  x                              z                                             x",
        "  x                          p                                                 x",
        "  x                          z         p                                       x",
        "  x                            p       z                                       x",
        "  x                            z                                               x",
        "  x                                                                            x",
        "  x                                   p                                        x",
        "  x                               o   z   p                                    x",
        "  x                           p   x       z                                    x",
        "  x                           z                                                x",
        "  x                                  p                                         x",
        "  x                          p       z                                         x",
        "  x                          z      p                                          x",
        "  x                                 z                                          x",
        "  x                         p   p                                              x",
        "  x        x  x   x         z   z                                              x",
        "  x        h  h   h                  p                                        xx",
        "  x           h                      z                               p         x",
        "  x        h                                                        uuu        x",
        "  x               h                                                uuuuu       x",
        "  xx                                                     p          uuu       xx",
        "  xh                 @  o     s                         uuu                    x",
        "  x        o  p o    x     =  x                        uuuuu                   x",
        "  x        x  x x x  xxxxxxxxxx                         uuu                    x",
        "  x   xx                                                                      xx",
        "  xx                                                p                  p       x",
        "  x                                                uuu                uuu      x",
        "  x                                               uuuuu              uuuuu     x",
        "  x                                                uuu                uuu     xx",
        "  xx                                                            p              x",
        "  x                                                 p          yyy             x",
        "  x                                     p          uuu        yyyyy            x",
        "  x                                    uuu        uuuuu        yyy            xx",
        "  xx          p x p     o x p         uuuuu        uuu                 p       x",
        "  x             h         h            uuu                            uuu      x",
        "  x                                                         p        uuuuu     x",
        "  x                                                        yyy        uuu     xx",
        "  xx   z   x =       =          x         o               yyyyy                x",
        "  x        xxxxxxxxxxxxxxxxxxxxxx x z    yyy               yyy                 x",
        "  x   x  z x!!!!!!!!!!!!!!!!!!!!x       yyyyy                   p              x",
        "  x        xxxxxxxxxxxxxxxxxxxxxxz   x   yyy        o          uuu            xx",
        "  x                                                yyy        uuuuu            x",
        "  x                                               yyyyy        uuu             x",
        "  x                                                yyy                  o      x",
        "  x                                                                    uuu    xx",
        "  x                                                            p      uuuuu    x",
        "  x                                                           uuu      uuu     x",
        "  x                                                          uuuuu             x",
        "  x                                                           uuu             xx",
        "  x                                                                  o         x",
        "  x                                                     p           uuu        x",
        "  x                                                    uuu         uuuuu       x",
        "  x                                                   uuuuu         uuu       xx",
        "  x                                                    uuu                     x",
        "  x                                                                            x",
        "  x                                                                            x",
        "  x                                                                           xx",
        "  x                                                                            x",
        "  x           xxxxxxxxxxx                                                      x",
        "  x           h      h                                    xxxxxxxx   x         x",
        "  x            h      h              x x                 xx          x        xx",
        "  x             h    h h             j j                xx           x         x",
        "  x            h     h                o                xx            x         x",
        "  x                o   h                              xxh            x         x",
        "  x   @       h h    h h      o                      xx   o          x        xx",
        "  xxxxxxxxxxxxxxxxzxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "                                                                                ",
        "                                                                                "
    ],




    ["  xxxxxxx                                                          x  ",
        "  x                                                                x  ",
        "  x                                                                x  ",
        "  x                                                                x  ",
        "  x                                                                x  ",
        "  x        yyyyyyyy    yyyyyy        yyyy    yyyyyyyyyyyy          x  ",
        "  x        yyyyyyyy    yyyyyyy       yyyy    yyy       yyy         x  ",
        "  x        yyy         yyyy yyy      yyyy    yyy        yyy        x  ",
        "  x        yyy         yyyy  yyy     yyyy    yyy         yyy       x  ",
        "  x        yyyyyyyy    yyyy   yyy    yyyy    yyy          yyy      x  ",
        "  x        yyyyyyyy    yyyy    yyy   yyyy    yyy           yyy     x  ",
        "  x        yyy         yyyy     yyy  yyyy    yyy          yyy      x  ",
        "  x        yyy         yyyy      yyy yyyy    yyy         yyy       x  ",
        "  x        yyyyyyyy    yyyy       yyyyyyy    yyy        yyy        x  ",
        "  x        yyyyyyyy    yyyy        yyyyyy    yyyyyyyyyyyy          x  ",
        "  x                                                                x  ",
        "  x     @                                                          x  ",
        "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "                                                                      ",
        "                                                                      "
    ],

];

if (typeof module != "undefined" && module.exports)
    module.exports = GAME_LEVELS;